# This is a basic workflow to help you get started with Actions

name: 🚀 Deploy website on push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Hello, world!
        
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.test.ipswichjaffa.org.uk
        username: ftp@test.ipswichjaffa.org.uk
        password: ${{ secrets.password }}
        server-dir: public_html/wp-content/plugins/test/
        dry-run: true
        exclude: |
          **/.git*
          **/.git*/**          
